config-version: 6
DropRandomItems: true #false to lost all inventory
language: enUs
available-worlds:
  - world
  - world_nether
  - world_the_end
PVP:
  Enable: true
  Kill-souls: 1
Mobs:
  Enable: true
  Percent: 100
  Amount: 1
ActionBar:
  Enable: true
General:
  Maximum-souls: 7
  Death-souls: 1
  Daily-souls: 1
  Souls-regenerate-duration: 60 #60 = 1s
  Respawn_souls: 3
  Lose-soul-message-after: 3
  First_join: 5
  Minimum_souls: 1